### ISSUE TITLE
Seeting presets to None has no visual feedback.

### ISSUE THREAD

**Issue by audetto** [juliagoda/antimicroX#101]
Just compiled from source on Ubuntu 19.10.

PS3 controller.
When I set the resents to WASD (or anything else)  it does work.
But when I then set it back to None (or the empty select in the dropdown) it does not have any gui feedback until antimicro is restarted or the relevant game pad pressed in which case the gui goes back to NO KEY.

**Comment by juliagoda** [comment]
I am sorry for misunderstanding, I thought that the problem occurs only for triggers
