### ISSUE TITLE
"Advanced" Button Is Grayed Out

### ISSUE THREAD

**Issue by dslamngu** [juliagoda/antimicroX#110]
Ubuntu 20.04 LTS Focal Fossa
Built from Source, with the dependencies listed in the readme:
sudo apt-get install extra-cmake-modules qttools5-dev qttools5-dev-tools libsdl2-dev libxi-dev libxtst-dev itstool gettext libqt5x11extras5-dev

I'm looking to use the Guide button for a set change. The "Advanced" button is not usable.

![Screenshot from 2020-05-09 17-08-19](https://user-images.githubusercontent.com/65096967/81487970-1b1d5900-9218-11ea-8a1f-d8d4e050d3b0.png)

**Comment by DaFunkShun** [comment]
You need to assign a key first (in my case even click it twice) before you can use the 'Advanced' button.

**Comment by juliagoda** [comment]
I know, it's easy to get lost in the program at the very beginning of using it, so I changed the behaviour of the button.

**Comment by dslamngu** [comment]
Interesting. Thank you!
