### ISSUE TITLE
Error when trying to install antimicroX-3.0.0-Linux.deb

### ISSUE THREAD

**Issue by Ahmed-E-86** [juliagoda/antimicroX#122]
I get this error message when trying to install `antimicroX-3.0.0-Linux.deb`:

```
dpkg: error processing archive ./antimicroX-3.0.0-Linux.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2:
 'Depends' field, invalid package name 'libsdl2-2.0-0;libqt5x11extras5': character ';' not allowed (only letters, digits and characters '-+._')
```

**Comment by juliagoda** [comment]
How is it now?

**Comment by Ahmed-E-86** [comment]
```
dpkg: error processing archive ./antimicroX-3.0.0-Linux.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2:
 'Depends' field, invalid package name 'qt5-default;libsdl2-2.0-0;libqt5x11extras5': character ';' not allowed (only letters, digits and characters '-+._')
```

**Comment by pktiuk** [comment]
I will soon deal with it.

**Comment by pktiuk** [comment]
I have hotfix for this.
https://github.com/juliagoda/antimicroX/pull/123

**Comment by pktiuk** [comment]
@Ahmed-E-86 
Could you check if .deb from this [link](https://send.firefox.com/download/304ec11ef99c4269/#3MZyHiYv7epBlX-lHhwIyw) works for you? (It will expire after 7 days from now)

@juliagoda 
Now you can just swap old .deb file from release site to new from link, or create new release (I know it is a bit too early, but in this case Github will do this work for you).
Sorry for my dumb mistake which caused this problem.

**Comment by juliagoda** [comment]
Ok, done

**Comment by Ahmed-E-86** [comment]
Thanks, I tested the file in your link, and it works fine. Great work from all of you 👍
