### ISSUE TITLE
Restore Windows installer

### ISSUE THREAD

**Issue by pktiuk** [juliagoda/antimicroX#131]
This project requires installer for Windows.

Original [antimicro](https://github.com/AntiMicro/antimicro) was compiled on Windows, but this fork doesn't have this feature yet.
Most of required components are already included in antimicro's repository.

It would be nice to also add portable version of AntiMicroX, it was done [there](https://github.com/AntiMicro/antimicro/blob/master/BuildOptions.md)

Things to do:
- [ ] compile AntimicroX on Windows
- [ ] Add build instructions to README
- [ ] Add building and uploading `exe` to github actions on release

**Comment by juliagoda** [comment]
It could be awesome, but I don't have Windows and to do that, you would need to create additional classes in project, that base on C++ and C too. You can't achieve this, only adding changes to CMakeLists. I noticed, that Github Sponsor has been around for Poland too for a while and I have to take a look at this.

**Comment by pktiuk** [comment]
I have copied missing files and CMakeLists configs from antimicro, but currently I have some problems with finding QT libraries by cmake. 
In case if someone more familiarized with Windows would like to try this porting I have published my changes here: https://github.com/pktiuk/antimicroX/tree/windows_compilation

**Comment by AliAsiri20** [comment]
Thank you pktiuk, You are an awesome guy. 
I have copied more lines from the old CmakeLIsts for the QT libraries, and I was able to run cmake without errors, but when I try to build the .exe file following the instructions on the old Antimicro page.  I get 6 errors related to UTF-8 unicode I think. I'll leave it for someone who knows what is he doing.
I just want to say thank you.

**Comment by rayman3003** [comment]
Can we have a windows build? 

Or antimicroX is an exclusive linux app?

**Comment by juliagoda** [comment]
> Can we have a windows build?

Could your read the posts above? Thank you

**Comment by rayman3003** [comment]
> I don't have Windows

https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by pktiuk** [comment]
@juliagoda  
We should also add tag "help wanted"

@rayman3003 
Installing Windows takes a lot of time to set up everything correctly (it takes much more time to install everything than in Linux, where we can download everything we need using one simple command).
Moreover, this task would be more suitable for a developer familiar with Windows, it's workflow and dependency management, so for this task, we need someone who is familiar with Windows and it's tools because he has to not only compile it but also create automated script installing dependencies and building binaries after every release.

**Comment by pktiuk** [comment]
Due to ending maintenance of AntiMicroX on this repository this issue is moved to a new repository and will and can be further tracked here: https://github.com/AntiMicroX/antimicroX/issues/4
