### ISSUE TITLE
Share user created controller profiles

### ISSUE THREAD

**Issue by Simao-Santos** [juliagoda/antimicroX#141]
I think that it would be a good idea to create a folder for user created controller profiles, or even a repository for them (just like the original [antimicro](https://github.com/AntiMicro/antimicro-profiles) had).
I think that it's a great way for people who, _on one hand_, just create profiles and know nothing of code contribute, and _on the other hand_, users who don't want to mess around or start from the ground up the configuration of the file, can just start playing.

There could be rules for these profiles, such as all the buttons should have names to indicate what they do, for example. This way we keep the standards of the application high.

I also think this could be a great way to ease new users into this great application!

**Comment by juliagoda** [comment]
I think that it's a very good idea. For that I will create a fork and we will continue the work

**Comment by juliagoda** [comment]
dc1ef923cfdfdfd4757d7ac32839fe38f5546a40
