### ISSUE TITLE
Do Antimicro profiles work in AntimicroX?

### ISSUE THREAD

**Issue by mrk310310** [juliagoda/antimicroX#146]
I don't have controller to test this. I shared some profiles for a game few years ago. Could I tell people if asked to use those .amgp files with AntimicroX?

**Comment by pktiuk** [comment]
They seem to be fully compatible.
Just look at this repo: https://github.com/juliagoda/antimicroX-profiles
Diffs from that repository and original fork to antimicro show, that only Readme was changed and original `.amgp` files remained unchanged.

**Comment by pktiuk** [comment]
You could also contribute your files to that library of configs.
Just: 
1. Create fork of that repo
2. Add your files (in folders)
3. Create pull Request
4. Wait and enjoy your contribution to something bigger. :)

**Comment by juliagoda** [comment]
Version 3.0.1 works with old profiles
