### ISSUE TITLE
Feature Request/Bug? - Auto Profiles Detect Specific Controller

### ISSUE THREAD

**Issue by trymeouteh** [juliagoda/antimicroX#59]
When I set an emulator application to open profile on my xbox 360 controller I found that if you had 1, 2, 3 or 4 of the same controller plugged in it will load the profile for every controller when the application started up. I don't know if this is a bug or not but it would be nice to have it so you have a auto profile only load a profile for a certain plugged in controller.

**Comment by juliagoda** [comment]
I think that I will collect all ideas and bugs and put in "Projects" to not forget about anything.

Yes. This is a bug. For system it's not a bug at all, because it just sees compliance and doesn't matter that occurs in many places, but for people it doesn't make sense... 

I will as first thinking about form, because I don't know yet, how system would separate profiles for the same controllers.

**Comment by trymeouteh** [comment]
I don't know much about software programming but when I plug a 2 or more Xbox controllers in, antimicro does detect "XInput Controller (Game Controller 1)" and "XInput Controller (Game Controller 2)". If you made it so the auto profile will load a profile by detect the active application, controller plugged in and the controller number are matching the auto profile that would be the easist way to my understanding.

If your gonna go by the controller unique ID (If controllers have such as thing) that is another approach but by doing so my computer may one day detect the player 1 controller as controller 2 and therefore load the auto profile for the wrong controller.

**Comment by juliagoda** [comment]
You have more than one controllers with the same names, right? Could you plug at least two in and give me results from this site [https://github.com/juliagoda/SDL_JoystickButtonNames](https://github.com/juliagoda/SDL_JoystickButtonNames) ?

```
git clone https://github.com/juliagoda/SDL_JoystickButtonNames.git
cd SDL_JoystickButtonNames/examples
cmake .
make
./checkInfo
```
I hope that it will work. I've got only one controller at the moment

**Comment by trymeouteh** [comment]
Sorry for the late reply. I would be willing to give my controller names but I am unable to compile the software. Can you please compile a release for Windows 64 bit? Then I can run it and tell you what my results are.

**Comment by juliagoda** [comment]
I don't have access to Windows at the moment, but I have some idea anyway. Pretty soon I will be implementing this. Btw I don't think that I will fight for Windows users, because I am alone with this app. Someone could help me in the future to clean that mess in CMakeLists, test functionalities on Windows and create new documentation for Windows. I just cannot do it all alone all the time. It's answer for #61 too. Sorry people

**Comment by juliagoda** [comment]
Could you check this feature out from last commit of test branch? Is it working for identical gamecontrollers? I've tried to ensure compatibility with old profiles with GUID - conversion should work with last selected profile, list of profiles and mappings but it hasn't been possible with other options so far

**Comment by trymeouteh** [comment]
Where do I download the test branch? Is it compiled? Cause I have no skills when it comes to compiling code.

Currently I have a Windows 10 machine and a Linux Mint machine but the xbox controller is not currently working on my Mint machine. I am new to Linux and I hope to get my controller to work soon on my Mint machine for gaming and Antimicro.

**Comment by juliagoda** [comment]
ok, thank you for answer. You don't have to hurry. You can just execute the above commands in the system console in the path of your choice

**Comment by trymeouteh** [comment]
I finally got an understanding of Linux as I have used it over the past few months and I got my controllers to work. I tried installing Antimicro 2.21 but it will not read my controller at all even through my controller work in all the games that have controller support. I also tried 2.23 with wine but the keyboard commands will not work.

I tried installing 2.23 but I have no skill compiling code from source. I know how to install flatpaks, appimages, deb files. Can you please make a release of this antimicro in one of those types and then I can test this out.

My distro of choice that I decided to use is Linux Mint 19.1

https://github.com/AntiMicro/antimicro/issues/278

**Comment by juliagoda** [comment]
Ok, I changed "commit" to "tag" in json file for flatpak

**Comment by trymeouteh** [comment]
I finally got antimicro 2.23 compiled on linux and working! I am not skilled with compiling and this was the first time I successfully compiled a linux app.

If you could make a flatpak or appimage of this and forked antimicro. I would gladly test it out and help with testing it on my Linux Mint machine.

**Comment by juliagoda** [comment]
I have two gamepads of the same model so I could finally check this out. If there are some problems with functionality, just let me know
