### ISSUE TITLE
Allow Set Switch (While Held) and KB button hold at the same time

### ISSUE THREAD

**Issue by maxigaz** [juliagoda/antimicroX#66]
Having read the [Wiki entry on set selection](https://github.com/AntiMicro/antimicro/wiki/Set-Selection) of the original (?) GitHub repo, I'd like to be able map both Set Switch (While Held) and pressing and holding of the left Shift key simultaneously on the right trigger of the gamepad. This would allow me to have a fairly suitable mapping for Fable: The Lost Chapters, close to the [Xbox controls](https://strategywiki.org/wiki/Fable/Controls). Is it possible to do that?

The wiki page mentions that you can right click on a button and enable one of the three Set Switch modes in the context menu. However, this option doesn't appear when I right click on either of the triggers.

Also, I've tried assigning Shift to the trigger and then left click on R Trigger → Shift_L → Advanced → Assignments → Select Set 2 While Held from drop down, but that doesn't seem to work.

**Comment by juliagoda** [comment]
Did it work in the old abandoned antimicro version that had support for Qt4? 
or would it be a new functionality that wasn't there?

**Comment by maxigaz** [comment]
I don't know because I hadn't even been aware antimicro had this feature until yesterday.

By the way, I've found a workaround for this particular situation: if I map two KB buttons to the same gamepad button (namely `O` for spell cycle and `Middle Mouse Button` for blocking to Triangle), there's actually no need to set up a condition to make Triangle behave differently depending on whether the trigger is held or not.

Although throughout my testing, antimicro froze a lot when I was in the Advanced window. I think it's best to create a new issue for that.

**Comment by CoreCoreCore** [comment]
I think you're looking for this...
![image](https://user-images.githubusercontent.com/59234936/71453259-ea002880-274f-11ea-989b-a4dc7c4e4464.png)

**Comment by juliagoda** [comment]
Is that what you wanted?

**Comment by maxigaz** [comment]
Sorry for the late reply.

@CoreCoreCore I don’t have Fable installed anymore to test it live, but if I go to Options menu → Key Checker and look at the displayed key code or play around in an input field (like setting a name for the axis in your last screenshot), it looks like it’s all working nicely now.

I didn’t have to set the distance eventually, but your second screenshot was very helpful because that option is what I needed. (I either missed it the first time or the UI has changed since then, I’m not sure.) Thanks for your input!
