### ISSUE TITLE
Segmentation fault when using command line

### ISSUE THREAD

**Issue by cyberconan** [juliagoda/antimicroX#70]
Hi! I have tried change from 2.23 to 2.24, everything appears ok with UI but not from command line. With main instance opened and minimized in tray, when I use commands like:
```
antimicro ~/Software/configs/antimicro/PCSXR.gamecontroller.amgp
antimicro --hidden ~/Software/configs/antimicro/WIN.gamecontroller.amgp
antimicro --profile-controller 1 ~/Software/configs/antimicro/DOS-NFS.gamecontroller.amgp
```
always crash:

> Application: antimicro (antimicro), signal: Segmentation fault
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> [Current thread is 1 (Thread 0x7f4982150240 (LWP 9920))]
> 
> Thread 3 (Thread 0x7f4979bc0700 (LWP 9922)):
> #0  0x00007f49854ca18c in read () from /usr/lib/libc.so.6
> #1  0x00007f49842029f0 in ?? () from /usr/lib/libglib-2.0.so.0
> #2  0x00007f4984250311 in g_main_context_check () from /usr/lib/libglib-2.0.so.0
> #3  0x00007f4984251a28 in ?? () from /usr/lib/libglib-2.0.so.0
> #4  0x00007f4984251b51 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
> #5  0x00007f4985bca9bc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
> #6  0x00007f4985b715ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
> #7  0x00007f49859a42f5 in QThread::exec() () from /usr/lib/libQt5Core.so.5
> #8  0x00007f498197db37 in ?? () from /usr/lib/libQt5DBus.so.5
> #9  0x00007f49859a5520 in ?? () from /usr/lib/libQt5Core.so.5
> #10 0x00007f498510357f in start_thread () from /usr/lib/libpthread.so.0
> #11 0x00007f49854d90e3 in clone () from /usr/lib/libc.so.6
> 
> Thread 2 (Thread 0x7f4980dd1700 (LWP 9921)):
> #0  0x00007f49854ce667 in poll () from /usr/lib/libc.so.6
> #1  0x00007f49841c9630 in ?? () from /usr/lib/libxcb.so.1
> #2  0x00007f49841cb2db in xcb_wait_for_event () from /usr/lib/libxcb.so.1
> #3  0x00007f4981a6d049 in ?? () from /usr/lib/libQt5XcbQpa.so.5
> #4  0x00007f49859a5520 in ?? () from /usr/lib/libQt5Core.so.5
> #5  0x00007f498510357f in start_thread () from /usr/lib/libpthread.so.0
> #6  0x00007f49854d90e3 in clone () from /usr/lib/libc.so.6
> 
> Thread 1 (Thread 0x7f4982150240 (LWP 9920)):
> [KCrash Handler]
> #6  0x000000000031002e in ?? ()
> #7  0x00007f4986d0455a in MainWindow::~MainWindow() () from /usr/lib/libantilib.so
> #8  0x000055600533b360 in ?? ()
> #9  0x00007f4985403ee3 in __libc_start_main () from /usr/lib/libc.so.6
> #10 0x000055600533d93e in ?? ()
> [Inferior 1 (process 9920) detached]

Thanks for keep this software alive.

PD: I'm using Archlinux and installed last version from [AUR](https://aur.archlinux.org/packages/antimicro/).

**Comment by juliagoda** [comment]
#74

**Comment by juliagoda** [comment]
Does project from last commit work properly? Does the error still appear?
