### ISSUE TITLE
Suggestion: Rename Project

### ISSUE THREAD

**Issue by trymeouteh** [juliagoda/antimicroX#71]
Since it is a fork I think renaming it would be a good idea. Maybe name it AntimicroX so others know this is a fork of it that will live on.

**Comment by juliagoda** [comment]
I think that the name sounds good. I'd like to know what others think about idea and name. I would like to hear from at least other 3 users, what they think about it

**Comment by Termuellinator** [comment]
Did you try to get in touch with https://github.com/AntiMicro/antimicro ? It seems they abandoned it. If they were willing to "hand it over" to you and mention your new repo in their readme.md, i think you should keep the name.
If you can't get a hold of them or they don't want to, then i think a distinct name would be a good idea. AntimicroX doesn't sound bad to me ^^

**Comment by juliagoda** [comment]
> Did you try to get in touch with https://github.com/AntiMicro/antimicro ?

Yes, I did, a long time ago. They never responded to my email or in a new thread, so we can finally decide on the name "AntimicroX". X would fit because of X11. I'll take care of everything as soon as I recover from dentist's appointments.

**Comment by CoreCoreCore** [comment]
I never got the name... why Antimicro... ?  Thank you for starting a fork!  =)

**Comment by juliagoda** [comment]
I don't know that either, but I have to admit that it's a specific name and that makes it easier to remember
