### ISSUE TITLE
Autoprofiles can't distinguish two joysticks

### ISSUE THREAD

**Issue by Termuellinator** [juliagoda/antimicroX#79]
I've got two T16000 joysticks and tried setting them up with autoprofiles. It seems the autoprofiles can't tell them apart, as they both get the same profile applied.
They both have the same GUID.
Setting both profiles manually works fine, but antimicro doesn't remember the set profiles on restart despite "open last profile" option being set.

**Comment by juliagoda** [comment]
#59
