### ISSUE TITLE
Build failure in Arch Linux

### ISSUE THREAD

**Issue by adelq** [juliagoda/antimicroX#83]
The project used to compile under Arch Linux, but does not with an up-to-date system today (2019-12-29). This problem applies to all recent commits/releases that used to build in the past, so I believe this is a problem related to upgraded system packages rather than a breaking change in antimicro. It also still builds fine under Ubuntu-based distros.

**Brief compile error**:
```
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/X11/extensions/XInput.h:52,
                 from /home/adel/projects/antimicro/src/x11extras.h:26,
                 from /home/adel/projects/antimicro/src/keyboard/virtualkeyboardmousewidget.cpp:34:
/usr/include/qt/QtCore/qurl.h: At global scope:
/usr/include/qt/QtCore/qurl.h:135:9: error: expected identifier before numeric constant
  135 |         None = 0x0,
      |         ^~~~
```

**Full error log:**
[error.log](https://github.com/juliagoda/antimicro/files/4008742/error.log)

**Library versions:**
g++: 9.2.0
cmake: 3.16.2
extra-cmake-modules: 5.65.0
qt5-tools: 5.14.0
sdl2: 2.0.10
libxi: 1.7.10
libxtst: 1.2.3
libx11: 1.6.9

**Comment by juliagoda** [comment]
Could you check if program from testing branch still builds under Ubuntu-based distro?

**Comment by adelq** [comment]
Yes, it compiles properly, I didn't have a chance to test all the features but it seems functional at a glance. It still does not build on Arch Linux though, I get the same error as previously.

**Comment by juliagoda** [comment]
I have the same problems but on master branch, but on testing branch I can build again. Did you try:

```
git clone -b testing https://github.com/juliagoda/antimicro.git
cd antimicro
mkdir build
cd build
cmake ..
make
sudo make install
```

**Comment by adelq** [comment]
You are correct, I built in a completely new environment and it compiled successfully, thanks for the quick fix!
