### ISSUE TITLE
Press 2 keyboard keys with 1 button on controller

### ISSUE THREAD

**Issue by loug42** [juliagoda/antimicroX#93]
I need to press up/down simultaneously - can't see how to do it.

**Comment by juliagoda** [comment]
I will create this functionality in the near future

**Comment by loug42** [comment]
Thank you for the prompt reply - I will check back on github for progress.

**Comment by juliagoda** [comment]
There it is - where slots are. Please create new issue when you find something.

**Comment by juliagoda** [comment]
#104
