### ISSUE TITLE
Feature Request: Exit/Close antimicroX via CLI

### ISSUE THREAD

**Issue by ultrez** [juliagoda/antimicroX#95]
It would be nice to have a Command Line to exit/close antimicroX. This would be useful if you use an arcade frontend. In most frontends you can start an additional program with the game. So launching antimicroX automatically wehen the game starts is no problem, but closing after the game has closed is difficult to set up without a CLI command (xpadder is using /c for example).

**Comment by juliagoda** [comment]
It's not a command line. It's a choice of shortcuts that work globally. It's in settings on the first tab. What do you think about it?

**Comment by ultrez** [comment]
It does the job and seems "easier" to use. Sounds good to me.

**Comment by juliagoda** [comment]
At first I wanted to give one universal command, but in total it is good to give users a choice. The standard shortcuts fully supported and working I took from this list on this [page](https://doc.qt.io/qt-5/qkeysequence.html)  . I wrote this in case anyone is surprised by the combination selection in the settings

**Comment by terencode** [comment]
With those last 2 commits (starting from 63fdb1f0f40169c4a2e246aed0326d13e14eaf43) I can't compile anymore:
```
[100%] Linking CXX executable bin/antimicroX
/usr/bin/ld: libantilib.so: undefined reference to `QGlobalShortcut::calcId(unsigned int, unsigned int)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/antimicroX.dir/build.make:114: bin/antimicroX] Error 1
make[1]: *** [CMakeFiles/Makefile2:159: CMakeFiles/antimicroX.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by juliagoda** [comment]
Please, try again. I've joined two qglobalshortcut classes to be sure and sir_lucjan has updated compilation flags on AUR

**Comment by terencode** [comment]
Yup, working thanks :)
