### ISSUE TITLE
Needing NUMPAD KEYS for older game, specifically KP_DEL

### ISSUE THREAD

**Issue by swntime** [juliagoda/antimicroX#96]
I am trying to map keys for an older game on Gentoo Linux. This game is "Search & Rescue 4: Coastal Heroes" My problem is there are several hard-coded functions bound to the NUMPAD. Enabling the spotlight for night missions requires KP_DEL. I can map some NUMPAD buttons with Fn+number keys on my keyboard, but the KP_DEL is nowhere to be found? I explored version 2.23 on Antimicro for Windows which actually features a graphical keyboard including the numpad keys. Why was this excluded on the Linux version? I then proceeded to map my needed key on the windows version and save my profile. Copied profile to USB and loaded into the Linux Antimicro. Unfortunately, my mapped key did not translate. Testing in-game, it in fact DID NOT TRANSLATE. I am lost at what to do next to resolve this issue?

**Comment by juliagoda** [comment]
Do you use antimicrox version 2.25 or antimicro 2.23?

**Comment by juliagoda** [comment]
Now there is the new option in settings
