### ISSUE TITLE
Set profile as default

### ISSUE THREAD

**Issue by MasterKTO** [juliagoda/antimicroX#97]
When using a custom profile and getting focus on an application unknown to antimicroX (like KDE Plasma shell or desktop), current profile is set to `<New>`, thus disabling gamepad navigation.

Moreover, in "Auto Profile" settings, I cannot assign a profile to the "Default" line. The prompt lets me select a profile but it is never saved, as it is no longer present when I open again Settings window.

**Comment by juliagoda** [comment]
Is it better now? Anything else missing?

**Comment by MasterKTO** [comment]
Thanks for you responsiveness.

Unfortunately, it changed nothing... Both problems still occur.

**Comment by juliagoda** [comment]
What version are you using? Antimicrox 2.25 from latest commit?

**Comment by MasterKTO** [comment]
When I noticed the problem, I was using 2.25 from AUR.

But for my last message, I built it from master.

**Comment by juliagoda** [comment]
Ok, I will work on it
